// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"仪表盘","path":"/dashboard","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"用户管理","path":"/users","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"商品管理","path":"/products","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"订单管理","path":"/orders","parentId":"ant-design-pro-layout","id":"5"},"6":{"name":"分类管理","path":"/categories","parentId":"ant-design-pro-layout","id":"6"},"7":{"name":"系统设置","path":"/settings","parentId":"ant-design-pro-layout","id":"7"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Dashboard" */'@/pages/Dashboard.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Users" */'@/pages/Users.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Products" */'@/pages/Products.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Orders" */'@/pages/Orders.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Categories" */'@/pages/Categories.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Settings" */'@/pages/Settings.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/media/vdc/WorkSpace/Personal/WechatOnlineShop/admin/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
